[versions]
agp = "8.13.2"
kotlin = "2.0.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.1"
composeBom = "2024.09.00"

#Hilt versions
hiltV = "2.56.2"
hiltNavigationComposeV = "1.2.0"

#ksp
kspV = "2.0.21-1.0.27"

#Retrofit
retrofitV = "3.0.0"
okhttp = "4.12.0"

#Room
roomV = "2.7.2"

#ViewModel
viewModelV = "2.10.0"

#Navigation
navigationComposeV = "2.9.6"

#Coil
coilVersion = "2.6.0"
material3 = "1.4.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }

#Hilt
hilt-android = { group = "com.google.dagger", name="hilt-android", version.ref = "hiltV" }
hilt-compiler = { group = "com.google.dagger", name="hilt-compiler", version.ref = "hiltV" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationComposeV"}

#Retrofit
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofitV" }
retrofit-gsonConverter = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofitV" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

#Room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomV" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomV" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomV" }

#ViewModel
viewModel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "viewModelV" }

#Navigation
androidx-navigation = { group = "androidx.navigation", name = "navigation-compose",  version.ref = "navigationComposeV" }

#Coil
androidx-coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coilVersion" }

#IconsExtended
androidx-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kspV"}
hilt = {id="com.google.dagger.hilt.android", version.ref = "hiltV"}

